server:
  servlet:
    context-path: /servera

  tomcat:
    uri-encoding: UTF-8

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true