apiVersion: apps/v1
kind: Deployment
metadata:
  name: servera-${BUILD_TIME}
  namespace: bigdata-demo
  labels:
    app: servera
    version: v${BUILD_TIME}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: servera
      version: v${BUILD_TIME}
  template:
    metadata:
      labels:
        app: servera
        version: v${BUILD_TIME}
    spec:
      containers:
        - name: servera
          image: ${ORIGIN_REPO}/${REPO}:${PRE_TAG}-${BUILD_TIME}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: servera
  namespace: bigdata-demo
  labels:
    app: servera
    service: servera
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: servera

